name: conda-build

on: [push, pull_request]

jobs:
  conda-build:
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v1
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
      - name: Install Node & Selenium
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pip altair nodejs selenium python-chromedriver-binary
          npm install -g vega-lite vega-cli canvas
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install -U pip wheel
          pip install pillow pypdf2  # optional test requirements
          pip install .
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest --doctest-modules altair_saver