name: lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: flake8-black-mypy
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --statistics
    - name: Check formatting with black
      run: |
        pip install black
        black --check .
    - name: Check types with mypy
      run: |
        pip install mypy
        mypy .
